[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.9.0"
edition = "2024"
license = "MIT"
rust-version = "1.85"

[workspace.dependencies]
romburak-rdb = { path = "crates/rdb" }
romburak-core = { path = "crates/core" }
romburak-store = { path = "crates/store" }
thiserror = "2"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
rayon = "1"
rusqlite = { version = "0.40", features = ["bundled", "fallible_uint"] }

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
unwrap_used = "warn"

[profile.release]
lto = "thin"
codegen-units = 1
