[package]
name = "rombro-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
rombro-core.workspace = true
rombro-store.workspace = true
anyhow.workspace = true
rombro-rdb.workspace = true
clap.workspace = true
rayon.workspace = true
serde_json = "1.0.151"

[[bin]]
name = "rombro"
path = "src/main.rs"
